### ISSUE TITLE
shaper.optimize() get very small value

### ISSUE THREAD

**Issue by jjasoncool** [panosz/alpha_shapes#16]
When I using the points cloud
[output_points.txt](https://github.com/user-attachments/files/16154425/output_points.txt)

```python
from alpha_shapes import Alpha_Shaper

shaper = Alpha_Shaper(self.points, normalize=True)
alpha_opt, shape = shaper.optimize()
print(f"Alpha shape optimize value:{alpha_opt}")
```

I will get 
Alpha shape optimize value:-1e-10

![圖片](https://github.com/panosz/alpha_shapes/assets/24731867/a40ffa14-137c-40e8-81e8-9e569a3478eb)

**Comment by panosz** [comment]
Thank you for this issue @jjasoncool 

It should be fixed now, although I am a bit confused about the figure you attached. When I plot the points you have uploaded I get the following
![image](https://github.com/panosz/alpha_shapes/assets/17211478/07127d2f-785d-4c1b-89ba-68202fd0e6cc)
