### ISSUE TITLE
How to get the x,y coordinate of the alpha_shape boundary

### ISSUE THREAD

**Issue by QJieWang** [panosz/alpha_shapes#4]
have reviewed `plot_alpha_shape` function, but it seems that the variable alpha_shape does not provide a direct way to access the x and y coordinates of the boundary points. I find this inconvenient and would like to know if there is any solution available.

**Comment by panosz** [comment]
@QJieWang I think you are right. Having a direct way to access the boundary (edges and vertices) would probably be convenient for some use cases. I guess a quick solution would be something along the lines of what is attempted at the `plot_alpha_shape` function.
Would you like to attempt to write it?

**Comment by panosz** [comment]
The `boundary.get_boundaries" method should do the job.
